In [2]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [6]:
import numpy as np
b=np.array([[1,2,3,4],[5,6,7,8]])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [7]:
import numpy as np
c=np.zeros((3,5))
print(c)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [9]:
import numpy as np
d=np.random.random((2,1))
print(d)

[[0.47958652]
 [0.60090748]]


In [15]:
e=np.arange(0,10,7)
print(e)

[0 7]


In [2]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
subarray=arr[0:2,1:3]
print(subarray)

[[2 3]
 [5 6]]


In [3]:
reversed_array=arr[::-1]
print(reversed_array)

[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [4]:
row1=arr[:,0]
print(row1)

[1 4 7]


In [5]:
col1=arr[0,:]
print(col1)

[1 2 3]


In [8]:
arr=np.array([10,20,30,40,50])
print(arr[0])

10


In [9]:
arr=np.array([10,20,30,40,50])
print(arr[4])

50


In [10]:
arr=np.array([10,20,30,40,50])
print(arr[-1])

50


In [11]:
arr=np.array([10,20,30,40,50])
print(arr[1:4])

[20 30 40]


In [13]:
arr=np.array([10,20,30,40,50])
print(arr[arr>25])

[30 40 50]


In [15]:
arr=np.array([10,20,30,40,50])
print(arr[[1,3]])

[20 40]


In [16]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[0,0])
print(arr[1,2])

1
6


In [20]:
#horizontal join
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
result=np.hstack((arr1,arr2))
print(result)

[[1 2 5 6]
 [3 4 7 8]]


In [18]:
result=np.vstack((arr1,arr2))
print(result)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [19]:
result=np.dstack((arr1,arr2))
print(result)

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [21]:
#numpy.split()
import numpy as np
arr=np.array[(1,2,3,4,5,6)]
result=np.split(arr,3)
print(result)

TypeError: 'builtin_function_or_method' object is not subscriptable

In [2]:
import numpy as np
arr1=[20,40,60,80,100]
arr2=[10,30,50,70,90]
a=np.array(arr1)
b=np.array(arr2)
print(a)
print(b)
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[ 20  40  60  80 100]
[10 30 50 70 90]
[ 30  70 110 150 190]
[10 10 10 10 10]
[ 200 1200 3000 5600 9000]
[2.         1.33333333 1.2        1.14285714 1.11111111]


In [3]:
print(a.dot(b))
sclr=3
print("Scalar value:",sclr)
print("Array:",a)
print("Result:",a*sclr)

19000
Scalar value: 3
Array: [ 20  40  60  80 100]
Result: [ 60 120 180 240 300]


In [4]:
import numpy as np
a=np.array([[10,20],[30,40]])
b=np.array([[3,7],[5,9]])
print(a%b)

[[1 6]
 [0 4]]


In [6]:
def my_func(x,y):
    if x>y:
        return x-y
    else:
        return x+y
arr1=[10,20,30,40,50]
arr2=[100,90,80,70,60]
vect_func=np.vectorize(my_func)
print("Array 1:",arr1)
print("Array 2:",arr2)
print("Result:",vect_func(arr1,arr2))

Array 1: [10, 20, 30, 40, 50]
Array 2: [100, 90, 80, 70, 60]
Result: [110 110 110 110 110]
